// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTZwGrWUij3LJWqUCU0Nh8yVRAYKmAEyQ',
    appId: '1:1018761893622:android:02e7ef0f3f972dd62c7ed7',
    messagingSenderId: '1018761893622',
    projectId: 'vgaddipati-cmsc5303-mobileapps',
    storageBucket: 'vgaddipati-cmsc5303-mobileapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSz5rkYa1ttXtaryx87RZTYYuZmHec62U',
    appId: '1:1018761893622:ios:736cb227867869722c7ed7',
    messagingSenderId: '1018761893622',
    projectId: 'vgaddipati-cmsc5303-mobileapps',
    storageBucket: 'vgaddipati-cmsc5303-mobileapps.appspot.com',
    iosClientId: '1018761893622-kq5npba37vbnko1dtokkoatdkdetppru.apps.googleusercontent.com',
    iosBundleId: 'edu.uco.vgaddipati.lesson3',
  );
}
